### PR TITLE
Add polyfill instructions

### PR DESCRIPTION
**Pull request by sstephenson**
Builds on #147.

### CODE REVIEW

**Comment by rainerborene** [comment]
It's not working.
```
yarn add v1.3.2
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@stimulus%2fpolyfill: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/home/rainer/Projects/memberkit/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by sstephenson** [comment]
I know. It hasn’t been published yet.

**Comment by sstephenson** [comment]
https://www.npmjs.com/package/@stimulus/polyfills
https://github.com/stimulusjs/stimulus/releases/tag/v1.1.0-beta.1

**Comment by rainerborene** [comment]
Thanks! :pray:

**Pull request merged**
