### PR TITLE
Polyfill Instructions

### PR DESCRIPTION
**Pull request by sunnyrjuneja**
I saw #135 and decided to try to help out. I based this on https://babeljs.io/docs/usage/polyfill/. Please let me know if there's any changes you would require.

### CODE REVIEW

**Comment by adammiribyan** [comment]
The package hasn't been published yet.

**Comment by rainerborene** [comment]
It should mention the `unpkg` url for the polyfill on README section about using it without a build system.

**Comment by rainerborene** [comment]
@sstephenson when does that package will be published?

**Comment by kud** [comment]
Yes please, could you tell us when it'll be published. I need it. :)

**Comment by kud** [comment]
Workaround for the moment:

- install

```
$ npm install core-js element-closest mutation-observer-inner-html-shim
```
- usage

```
import "core-js/fn/array/find"
import "core-js/fn/array/find-index"
import "core-js/fn/array/from"
import "core-js/fn/map"
import "core-js/fn/object/assign"
import "core-js/fn/promise"
import "core-js/fn/set"
import "element-closest"
import "mutation-observer-inner-html-shim"
```

**Pull request merged**
